name: Code Quality
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
  pull_request:
jobs:
  Testing:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test API
        uses: KristianFJones/npm-run-action@alternative
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FIRST_YEAR: '628682710487007242'
          SECOND_YEAR: '629098890876157973'
          GRADUATED: '629098917585354772'
          TEST_USER: '628386142076796948'
          TEST_GUILD: '628682632171094039'
        with:
          scriptName: 'test'
          scriptPath: './'
