name: Code Quality
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
  pull_request:
jobs:
  Testing:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test API
        uses: KristianFJones/npm-run-action@alternative
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FIRST_YEAR: 628386864352460836
          SECOND_YEAR: 628386928831627274
          GRADUATED: 628393889035845653
          TEST_USER: 628386142076796948
          TEST_GUILD: 198215820223053825
        with:
          scriptName: 'test'
          scriptPath: ''
